# \u542F\u52A8\u7AEF\u53E3
server:
  port: 9000

dubbo:
  application:
    name: dubbo-client
  registry:
#    address: zookeeper://127.0.0.1:2181
    address: 127.0.0.1:8841,127.0.0.1:8842,127.0.0.1:8843 # 注册到nacos
    protocol: nacos

  metadata-report:
#    address: zookeeper://127.0.0.1:2181
#    address: nacos://127.0.0.1:8841 # 注册到nacos


  # 全局超时时间
  consumer:
    timeout: 4000
    # 重试次数（默认2）
    retries: 2